### ISSUE TITLE
No amass output when I ran this command

### ISSUE THREAD

**Issue by l50** [Sandarmann/dr_robot#18]
```
drrobot gather -turbo -hack -dump -amass <target site>
```
Although the other two did appear to run to completion.

**Comment by l50** [comment]
Never mind, saw that it got moved to `~/.drrobot`. Jetlag is a bitch.

**Comment by l50** [comment]
More helpful info:
```
2019-09-25 11:20:15,960 {/Users/user/programs/dr_robot-al/src/robot_api/api/dockerize.py:127}:  [!] BuildError: Amass
Traceback (most recent call last):
  File "/Users/user/programs/dr_robot-al/src/robot_api/api/dockerize.py", line 122, in build
  ┊ use_config_proxy=True)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/models/images.py", line 287, in build
  ┊ raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: COPY failed: stat /var/lib/docker/overlay2/da80d4688f8f8f7a3450506e2ef0a2de5e6cbf79c49e5e1d13d61c64785beb12/merged/go/src/github.com/OWASP/Amass/wordlists: no such file or directory
2019-09-25 11:20:18,895 {/Users/user/programs/dr_robot-al/src/robot_api/api/dockerize.py:188}:  [!] ImageNotFound: Amass
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
  ┊ response.raise_for_status()
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
  ┊ raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/models/containers.py", line 803, in run
  ┊ detach=detach, **kwargs)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/models/containers.py", line 861, in create
  ┊ resp = self.client.api.create_container(**create_kwargs)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/container.py", line 429, in create_container
  ┊ return self.create_container_from_config(config, name)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/container.py", line 440, in create_container_from_config
  ┊ return self._result(res, True)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
  ┊ self._raise_for_status(response)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
  ┊ raise create_api_error_from_http_exception(e)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
  ┊ raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: amass:amass")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
  ┊ response.raise_for_status()
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
  ┊ raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/create?tag=amass&fromImage=amass

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/programs/dr_robot-al/src/robot_api/api/dockerize.py", line 179, in run
  ┊ volumes=volumes)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/models/containers.py", line 805, in run
  ┊ self.client.images.pull(image, platform=platform)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/models/images.py", line 444, in pull
  ┊ repository, tag=tag, stream=True, **kwargs
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/image.py", line 414, in pull
  ┊ self._raise_for_status(response)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
  ┊ raise create_api_error_from_http_exception(e)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
  ┊ raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for amass, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
2019-09-25 11:33:41,562 {/Users/user/programs/dr_robot-al/src/robot_api/api/dockerize.py:127}:  [!] BuildError: Amass
Traceback (most recent call last):
  File "/Users/user/programs/dr_robot-al/src/robot_api/api/dockerize.py", line 122, in build
  ┊ use_config_proxy=True)
  File "/Users/user/.local/share/virtualenvs/dr_robot-al-LzGhnNky/lib/python3.7/site-packages/docker/models/images.py", line 287, in build
  ┊ raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: COPY failed: stat /var/lib/docker/overlay2/c14e2ccf512a220f1ffb10b04381c1a9321c24dc48a2b58d4b3a7e813ce5fd73/merged/go/src/github.com/OWASP/Amass/wordlists: no such file or directory
```

**Comment by CrimsonK1ng** [comment]
Fixed in refactor
